apiVersion: v1
kind: Service
metadata:
  name: workbook-exporter-svc
  namespace: workbook-exporter
  labels:
    app: workbook-exporter
spec:
  ports:
  - port: 9701
    targetPort: 9701
    protocol: TCP
  selector:
    app: workbook-exporter
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workbook-exporter-dep
  namespace: workbook-exporter
  labels:
    app: workbook-exporter
spec:
  replicas: 2
  selector:
    matchLabels:
      app: workbook-exporter
  template:
    metadata:
      labels:
        app: workbook-exporter
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: wbe-configmap
      containers:
      - name: workbook-exporter
        image: tobiasbp/workbook_exporter:latest
        ports:
          - containerPort: 9701
        volumeMounts:
          - name: config-volume
            mountPath: /etc/workbook_exporter.yml
            subPath: workbook_exporter.yml
        env:
          - name: WORKBOOK_URL
            valueFrom:
              secretKeyRef:
                name: wbe-secret
                key: workbook_url
          - name: WORKBOOK_USER
            valueFrom:
              secretKeyRef:
                name: wbe-secret
                key: workbook_user
          - name: WORKBOOK_PASSWORD
            valueFrom:
              secretKeyRef:
                name: wbe-secret
                key: workbook_password
