{
 "title": "Workbook (Projects)",
 "tags": [
  "Workbook",
  "Projects"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "company_id", "query": "1" },
   { "name": "wb_job", "query": "your_prometheus_job" }
  ]
 },
 "panels": [
  {
   "title": "Jobs worked on",
   "type": "graph",
   "description": "Number of jobs with time entered for the previous 7 days.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "workbook_time_entry_jobs_total{company_id=~\"[[company_id]]\",job=~\"[[wb_job]]\"}",
     "legendFormat": "{{department_name}}"
    }
   ]
  },
  {
   "title": "Jobs (Billable)",
   "type": "graph",
   "description": "Number of active billable jobs and their age.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "workbook_jobs_age_days_bucket{billable=\"1\",company_id=~\"[[company_id]]\",job=~\"[[wb_job]]\"}",
     "legendFormat": "{{le}} days of less"
    }
   ]
  },
  {
   "title": "Departments: Target difference",
   "type": "graph",
   "description": "The difference between target and percentage of billable time for the previous 7 days.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(workbook_time_entry_hours_billable{company_id=~\"[[company_id]]\",days=\"7\",job=~\"[[wb_job]]\"}/workbook_time_entry_hours_capacity_total{company_id=~\"[[company_id]]\",days=\"7\",job=~\"[[wb_job]]\"}) - ignoring(days)(workbook_employees_profit_ratio_sum{company_id=~\"[[company_id]]\",job=~\"[[wb_job]]\"}/workbook_employees_profit_ratio_count{company_id=~\"[[company_id]]\",job=~\"[[wb_job]]\"})",
     "legendFormat": "{{department_name}}"
    }
   ]
  },
  {
   "title": "Jobs (Non billable)",
   "type": "graph",
   "description": "Number of active non billable jobs and their age.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "workbook_jobs_age_days_bucket{billable=\"0\",company_id=~\"[[company_id]]\",job=~\"[[wb_job]]\"}",
     "legendFormat": "{{le}} days of less"
    }
   ]
  },
  {
   "title": "Departments: Billable time",
   "type": "graph",
   "description": "The percentage of billable time for the previous 7 days.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(workbook_time_entry_hours_billable{company_id=~\"[[company_id]]\",days=\"7\",job=~\"[[wb_job]]\"}/workbook_time_entry_hours_capacity_total{company_id=~\"[[company_id]]\",days=\"7\",job=~\"[[wb_job]]\"})",
     "legendFormat": "{{department_name}}"
    }
   ]
  },
  {
   "title": "Active clients",
   "type": "graph",
   "description": "Number of clients with active jobs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "repeat": "Company",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "workbook_active_customers_billable_jobs{company_id=~\"[[company_id]]\",job=~\"[[wb_job]]\"}",
     "legendFormat": "Billable"
    },
    {
     "expr": "workbook_active_customers_total_jobs{company_id=~\"[[company_id]]\",job=~\"[[wb_job]]\"}-workbook_active_customers_billable_jobs{company_id=~\"[[company_id]]\",job=~\"[[wb_job]]\"}",
     "legendFormat": "Non billable"
    },
    {
     "expr": "workbook_active_customers_total_jobs{company_id=~\"[[company_id]]\",job=~\"[[wb_job]]\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Departments: Time entered",
   "type": "graph",
   "description": "The ratio of hours entered to expected hours for the previous 7 days. Above 100% is overtime.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "workbook_time_entry_hours_total{company_id=~\"[[company_id]]\",days=\"7\",job=~\"[[wb_job]]\"}/workbook_time_entry_hours_capacity_total{company_id=~\"[[company_id]]\",days=\"7\",job=~\"[[wb_job]]\"}",
     "legendFormat": "{{department_name}}"
    }
   ]
  },
  {
   "title": "Time registered previous 7 days",
   "type": "graph",
   "description": "The total number of hours registered pr. department during the previous 7 days.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "repeat": "department_name",
   "yaxes": [
    { "format": "h" }
   ],
   "targets": [
    {
     "expr": "workbook_time_entry_hours_total{company_id=~\"[[company_id]]\",days=\"7\",job=~\"[[wb_job]]\"}",
     "legendFormat": "{{department_name}}"
    }
   ]
  }
 ]
}