{
 "title": "Workbook (Projects)",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "company_id", "query": "1" },
   { "name": "wb_job", "query": "your_prometheus_job" }
  ]
 },
 "panels": [
  {
   "title": "Departments: Jobs worked  on",
   "type": "graph",
   "description": "The number of jobs worked on for the previous 7 days.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "workbook_time_entry_jobs_total{company_id=~\"[[company_id]]\",job=~\"[[wb_job]]\"}",
     "legendFormat": "{{department_name}}"
    }
   ]
  },
  {
   "title": "No of active clients",
   "type": "graph",
   "description": "No of clients with active jobs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "repeat": "Company",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "workbook_active_customers_billable_jobs{company_id=~\"[[company_id]]\",job=~\"[[wb_job]]\"}",
     "legendFormat": "Billable"
    },
    {
     "expr": "workbook_active_customers_total_jobs{company_id=~\"[[company_id]]\",job=~\"[[wb_job]]\"}-workbook_active_customers_billable_jobs{company_id=~\"[[company_id]]\",job=~\"[[wb_job]]\"}",
     "legendFormat": "Non billable"
    },
    {
     "expr": "workbook_active_customers_total_jobs{company_id=~\"[[company_id]]\",job=~\"[[wb_job]]\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Departments: Target difference",
   "type": "graph",
   "description": "The difference between target and percentage of billable time for the previous 7 days.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(workbook_time_entry_hours_billable{company_id=~\"[[company_id]]\",days=\"7\",job=~\"[[wb_job]]\"}/workbook_time_entry_hours_capacity_total{company_id=~\"[[company_id]]\",days=\"7\",job=~\"[[wb_job]]\"}) - ignoring(days)(workbook_employees_profit_ratio_sum{company_id=~\"[[company_id]]\",job=~\"[[wb_job]]\"}/workbook_employees_profit_ratio_count{company_id=~\"[[company_id]]\",job=~\"[[wb_job]]\"})",
     "legendFormat": "{{department_name}}"
    }
   ]
  },
  {
   "title": "Job age (Billable)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "d" }
   ],
   "targets": [
    {
     "expr": "workbook_jobs_age_days_sum{job=~\"[[wb_job]]\",company_id=~\"[[company_id]]\",billable=\"1\"}/workbook_jobs_age_days_count{job=~\"[[wb_job]]\",company_id=~\"[[company_id]]\",billable=\"1\"}",
     "legendFormat": "Average"
    },
    {
     "expr": "histogram_quantile(0.2, workbook_jobs_age_days_bucket{billable=\"1\",company_id=~\"[[company_id]]\",job=~\"[[wb_job]]\"})",
     "legendFormat": "20th percentile"
    },
    {
     "expr": "histogram_quantile(0.4, workbook_jobs_age_days_bucket{billable=\"1\",company_id=~\"[[company_id]]\",job=~\"[[wb_job]]\"})",
     "legendFormat": "40th percentile"
    },
    {
     "expr": "histogram_quantile(0.6, workbook_jobs_age_days_bucket{billable=\"1\",company_id=~\"[[company_id]]\",job=~\"[[wb_job]]\"})",
     "legendFormat": "60th percentile"
    },
    {
     "expr": "histogram_quantile(0.8, workbook_jobs_age_days_bucket{billable=\"1\",company_id=~\"[[company_id]]\",job=~\"[[wb_job]]\"})",
     "legendFormat": "80th percentile"
    },
    {
     "expr": "histogram_quantile(0.9, workbook_jobs_age_days_bucket{billable=\"1\",company_id=~\"[[company_id]]\",job=~\"[[wb_job]]\"})",
     "legendFormat": "90th percentile"
    },
    {
     "expr": "workbook_jobs_age_days_bucket{billable=\"1\",company_id=~\"[[company_id]]\",job=~\"[[wb_job]]\",le=\"15\"}",
     "legendFormat": "Jobs 15 days or less old"
    }
   ]
  },
  {
   "title": "Departments: Billable time",
   "type": "graph",
   "description": "The percentage of billable time for the previous 7 days.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(workbook_time_entry_hours_billable{company_id=~\"[[company_id]]\",days=\"7\",job=~\"[[wb_job]]\"}/workbook_time_entry_hours_capacity_total{company_id=~\"[[company_id]]\",days=\"7\",job=~\"[[wb_job]]\"})",
     "legendFormat": "{{department_name}}"
    }
   ]
  },
  {
   "title": "Job age (Non billable)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "d" }
   ],
   "targets": [
    {
     "expr": "workbook_jobs_age_days_sum{job=~\"[[wb_job]]\",company_id=~\"[[company_id]]\",billable=\"1\"}/workbook_jobs_age_days_count{job=~\"[[wb_job]]\",company_id=~\"[[company_id]]\",billable=\"0\"}",
     "legendFormat": "Average"
    },
    {
     "expr": "histogram_quantile(0.2, workbook_jobs_age_days_bucket{billable=\"0\",company_id=~\"[[company_id]]\",job=~\"[[wb_job]]\"})",
     "legendFormat": "20th percentile"
    },
    {
     "expr": "histogram_quantile(0.4, workbook_jobs_age_days_bucket{billable=\"0\",company_id=~\"[[company_id]]\",job=~\"[[wb_job]]\"})",
     "legendFormat": "40th percentile"
    },
    {
     "expr": "histogram_quantile(0.6, workbook_jobs_age_days_bucket{billable=\"0\",company_id=~\"[[company_id]]\",job=~\"[[wb_job]]\"})",
     "legendFormat": "60th percentile"
    },
    {
     "expr": "histogram_quantile(0.8, workbook_jobs_age_days_bucket{billable=\"0\",company_id=~\"[[company_id]]\",job=~\"[[wb_job]]\"})",
     "legendFormat": "80th percentile"
    },
    {
     "expr": "histogram_quantile(0.9, workbook_jobs_age_days_bucket{billable=\"0\",company_id=~\"[[company_id]]\",job=~\"[[wb_job]]\"})",
     "legendFormat": "90th percentile"
    },
    {
     "expr": "workbook_jobs_age_days_bucket{billable=\"0\",company_id=~\"[[company_id]]\",job=~\"[[wb_job]]\",le=\"15\"}",
     "legendFormat": "Jobs 15 days or less old"
    }
   ]
  },
  {
   "title": "Departments: Time entered",
   "type": "graph",
   "description": "The ratio of hours entered to expected hours for the previous 7 days. Above 100% is overtime.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "workbook_time_entry_hours_total{company_id=~\"[[company_id]]\",days=\"7\",job=~\"[[wb_job]]\"}/workbook_time_entry_hours_capacity_total{company_id=~\"[[company_id]]\",days=\"7\",job=~\"[[wb_job]]\"}",
     "legendFormat": "{{department_name}}"
    }
   ]
  },
  {
   "title": "Departments: Hours worked last 7 days",
   "type": "graph",
   "description": "The total number of hours registered for all people in the department during the previous 7 days.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "repeat": "department_name",
   "yaxes": [
    { "format": "h" }
   ],
   "targets": [
    {
     "expr": "workbook_time_entry_hours_total{company_id=~\"[[company_id]]\",days=\"7\",job=~\"[[wb_job]]\"}",
     "legendFormat": "{{department_name}}"
    }
   ]
  }
 ]
}