{
 "title": "Workbook (Finance)",
 "description": "A dashboard with financial data from Workbook.",
 "tags": [
  "Workbook",
  "Finance"
 ],
 "time": { "from": "now-30d", "to": "now-5m" },
 "templating": {
  "list": [
   { "name": "company_id", "query": "1" },
   { "name": "wb_job", "query": "your_prometheus_job" },
   {
    "name": "currency",
    "query": "label_values(workbook_debit_due_count{company_id=~\"[[company_id]]\",job=~\"[[wb_job]]\"},currency)"
   },
   {
    "name": "finance_accounts",
    "label": "Finance accounts",
    "query": "label_values(workbook_finance_account_balance{currency=~\"[[currency]]\",company_id=~\"[[company_id]]\",job=~\"[[wb_job]]\"}, account_description)"
   },
   {
    "name": "change_days",
    "label": "Days to use when calculating change",
    "query": "1,7,14,30,180,360"
   },
   {
    "name": "prediction_base_days",
    "label": "Number of days of data to base prediction on",
    "query": "30,60,90,120,180,360"
   },
   {
    "name": "prediction_future_days",
    "label": "Number of days in the future to predict for",
    "query": "30,60,90,120,180,360"
   }
  ]
 },
 "panels": [
  {
   "title": "Account balance ([[currency]])",
   "type": "graph",
   "description": "Current balance of accounts. Select accounts to include  form menu \"Finance accounts\"",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "workbook_finance_account_balance{company_id=~\"[[company_id]]\",job=~\"[[wb_job]]\",currency=~\"[[currency]]\",account_description=~\"[[finance_accounts]]\"}",
     "legendFormat": "{{account_description}}"
    }
   ]
  },
  {
   "title": "Debit & Credit ([[currency]])",
   "type": "graph",
   "description": "Money owed by us (Credit) and money owed to us (Debit).",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "abs(workbook_credit_total_sum{company_id=~\"[[company_id]]\",job=~\"[[wb_job]]\",currency=~\"[[currency]]\"})",
     "legendFormat": "Credit total"
    },
    {
     "expr": "abs(workbook_credit_due_sum{company_id=~\"[[company_id]]\",job=~\"[[wb_job]]\",currency=~\"[[currency]]\"})",
     "legendFormat": "Credit due"
    },
    {
     "expr": "workbook_debit_total_sum{company_id=~\"[[company_id]]\",job=~\"[[wb_job]]\",currency=~\"[[currency]]\"}",
     "legendFormat": "Debit total"
    },
    {
     "expr": "workbook_debit_due_sum{company_id=~\"[[company_id]]\",job=~\"[[wb_job]]\",currency=~\"[[currency]]\"}",
     "legendFormat": "Debit due"
    },
    {
     "expr": "workbook_debit_total_sum{company_id=~\"[[company_id]]\",job=~\"[[wb_job]]\"}- abs(workbook_credit_total_sum{company_id=~\"[[company_id]]\",job=~\"[[wb_job]]\"})",
     "legendFormat": "Difference total"
    },
    {
     "expr": "workbook_debit_due_sum{company_id=~\"[[company_id]]\",job=~\"[[wb_job]]\"}- abs(workbook_credit_due_sum{company_id=~\"[[company_id]]\",job=~\"[[wb_job]]\"})",
     "legendFormat": "Difference due"
    }
   ]
  },
  {
   "title": "Accounts balance prediction [[prediction_future_days]] days ([[currency]])",
   "type": "graph",
   "description": "Predicted balance of accounts [[prediction_future_days]] days in the future based on data for the previous [[prediction_base_days]] days. Select accounts to include  form menu \"Finance accounts\"",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "predict_linear(workbook_finance_account_balance{company_id=~\"[[company_id]]\",job=~\"[[wb_job]]\",currency=~\"[[currency]]\",account_description=~\"[[finance_accounts]]\"}[${prediction_base_days}d], ${prediction_future_days}*24*60^2)",
     "legendFormat": "{{account_description}}"
    }
   ]
  },
  {
   "title": "Debitors & Creditors",
   "type": "graph",
   "description": "Number of debitors (They own us money) and creditors (We own them money).",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "workbook_credit_total_count{company_id=~\"[[company_id]]\",job=~\"[[wb_job]]\"}",
     "legendFormat": "Creditors total"
    },
    {
     "expr": "workbook_credit_due_count{company_id=~\"[[company_id]]\",job=~\"[[wb_job]]\"}",
     "legendFormat": "Creditors due"
    },
    {
     "expr": "workbook_debit_total_count{company_id=~\"[[company_id]]\",job=~\"[[wb_job]]\"}",
     "legendFormat": "Debitors total"
    },
    {
     "expr": "workbook_debit_due_count{company_id=~\"[[company_id]]\",job=~\"[[wb_job]]\"}",
     "legendFormat": "Debitors due"
    },
    {
     "expr": "workbook_debit_total_count{company_id=~\"[[company_id]]\",job=~\"[[wb_job]]\"}-workbook_credit_total_count{company_id=~\"[[company_id]]\",job=~\"[[wb_job]]\"}",
     "legendFormat": "Difference total"
    },
    {
     "expr": "workbook_debit_due_count{company_id=~\"[[company_id]]\",job=~\"[[wb_job]]\"}-workbook_credit_due_count{company_id=~\"[[company_id]]\",job=~\"[[wb_job]]\"}",
     "legendFormat": "Difference due"
    }
   ]
  },
  {
   "title": "Accounts balance change [[change_days]] days ([[currency]])",
   "type": "graph",
   "description": "Change in account balance compared with [[change_days]] days in the past. Select accounts to include  form menu \"Finance accounts\"",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(workbook_finance_account_balance{company_id=~\"[[company_id]]\",account_description=~\"[[finance_accounts]]\",job=~\"[[wb_job]]\"}[${change_days}d])",
     "legendFormat": "{{account_description}}"
    }
   ]
  },
  {
   "title": "Employment length",
   "type": "heatmap",
   "description": "A histogram over time. Imagine it being viewed from above. The lighter the color, the higher the bar.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "workbook_employees_days_employed_bucket{company_id=~\"[[company_id]]\",job=~\"[[wb_job]]\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Departments: Sums of hourly costs ([[currency]])",
   "type": "graph",
   "description": "The sums of hourly costs pr. department.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "workbook_employees_hours_cost_sum{company_id=~\"[[company_id]]\",job=~\"[[wb_job]]\",currency=~\"[[currency]]\"}",
     "legendFormat": "{{department_name}}"
    },
    {
     "expr": "sum(workbook_employees_hours_cost_sum{company_id=~\"[[company_id]]\",job=~\"[[wb_job]]\",currency=~\"[[currency]]\"})/count(workbook_employees_hours_cost_sum{company_id=~\"[[company_id]]\",job=~\"[[wb_job]]\"})",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Departments: Average hourly cost ([[currency]])",
   "type": "graph",
   "description": "The average hourly cost of people in a department.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "workbook_employees_hours_cost_sum{company_id=~\"[[company_id]]\",job=~\"[[wb_job]]\",currency=~\"[[currency]]\"}/workbook_employees_hours_cost_count{company_id=~\"[[company_id]]\",job=~\"[[wb_job]]\",currency=~\"[[currency]]\"}",
     "legendFormat": "{{department_name}}"
    }
   ]
  }
 ]
}